# Generated by Django 5.2.5 on 2026-04-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_categoria_producto_tipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=20),
        ),
    ]
